"""empty message

Revision ID: 438709da2e50
Revises: 85ee10ad1330
Create Date: 2021-04-20 12:41:56.051819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '438709da2e50'
down_revision = '85ee10ad1330'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('image', sa.String(length=150), nullable=True))
    op.add_column('tag', sa.Column('subtitle', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tag', 'subtitle')
    op.drop_column('tag', 'image')
    # ### end Alembic commands ###
