"""empty message

Revision ID: 85ee10ad1330
Revises: 85fc53080682
Create Date: 2021-04-20 12:36:51.759352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85ee10ad1330'
down_revision = '85fc53080682'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('image', sa.String(length=150), nullable=True))
    op.add_column('tag', sa.Column('sub_title', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tag', 'sub_title')
    op.drop_column('tag', 'image')
    # ### end Alembic commands ###
