"""empty message

Revision ID: 85fc53080682
Revises: 99d2c1d0e92d
Create Date: 2021-03-24 16:19:58.528302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85fc53080682'
down_revision = '99d2c1d0e92d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('photos', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'photos')
    # ### end Alembic commands ###
